# Generated by Django 4.0.4 on 2022-04-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('name', models.CharField(max_length=100)),
                ('ID', models.IntegerField()),
                ('specialization', models.CharField(max_length=250)),
            ],
        ),
    ]
