# Generated by Django 4.0.4 on 2022-04-25 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='register',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='Type Name', max_length=100),
        ),
    ]
